### ISSUE TITLE
Error response from daemon: Container is not running

### ISSUE THREAD

**Issue by piyagehi** [karton/karton#17]
When trying to execute `karton run <image>` after building the image, the following error appears: 
```txt
Error response from daemon: Container <container> is not running
```
On running the image from Docker Desktop (this was tested on an M1 MacBook Pro), the container immediately stops running. The logs show the following message:

<img width="1192" alt="Screen Shot 2022-06-17 at 12 36 30 AM" src="https://user-images.githubusercontent.com/45182159/174159297-d69fd35a-c1b1-48a3-940e-0c060d547215.png">

Solution:
Edit all instances of the shebang line in the source code from `#! /usr/bin/env python` to `#! /usr/bin/env python3` and build karton.

**Comment by barisione** [comment]
(Sorry for the late reply. It looks like I stopped getting notifications for this project from GitHub.)

Using Python 2 was a deliberate choice because, when I wrote Karton, macOS came with Python 2.7 installed and `python` was available on all Linux distros I know of (the ones using Python 3 had a symlink so that `python` started Python 3).

Interestingly, Apple did this change in a minor update 🤦. See https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/.
